// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhDRBV4o6QTxTX3apSrF_TzZhbV42EXJ4',
    appId: '1:665523992889:web:75d8e731c22b14921f90e8',
    messagingSenderId: '665523992889',
    projectId: 'expense-tracker-3665a',
    authDomain: 'expense-tracker-3665a.firebaseapp.com',
    storageBucket: 'expense-tracker-3665a.firebasestorage.app',
    measurementId: 'G-ZTDJ1LXS9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrSMXBk9EhG3B1GRQkWQGxZOJUqtU75lk',
    appId: '1:665523992889:android:25715b63adb7113d1f90e8',
    messagingSenderId: '665523992889',
    projectId: 'expense-tracker-3665a',
    storageBucket: 'expense-tracker-3665a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXaWpmLVK-WcgVUfJcfXtf-chJmr8aj8M',
    appId: '1:665523992889:ios:d52abf8d533aceda1f90e8',
    messagingSenderId: '665523992889',
    projectId: 'expense-tracker-3665a',
    storageBucket: 'expense-tracker-3665a.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXaWpmLVK-WcgVUfJcfXtf-chJmr8aj8M',
    appId: '1:665523992889:ios:d52abf8d533aceda1f90e8',
    messagingSenderId: '665523992889',
    projectId: 'expense-tracker-3665a',
    storageBucket: 'expense-tracker-3665a.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhDRBV4o6QTxTX3apSrF_TzZhbV42EXJ4',
    appId: '1:665523992889:web:a9790f7b613fca391f90e8',
    messagingSenderId: '665523992889',
    projectId: 'expense-tracker-3665a',
    authDomain: 'expense-tracker-3665a.firebaseapp.com',
    storageBucket: 'expense-tracker-3665a.firebasestorage.app',
    measurementId: 'G-5LFM1ST9M1',
  );
}
